### ISSUE TITLE
BBSmile funktioniert nicht

### ISSUE THREAD

**Issue by Alexalter** [zikula-ev/BBSmile#19]
BBSmile funktioniert nicht, aber früh war alles ok, jetzt zeigt unter smile "loading" bitte Hilfe

hier ist ein beispiel http://al-werner.de/eternizer/edit/ot/entry

Grüß Alex

**Comment by detlefmue** [comment]
@Alexalter Bei mir erscheint das gleich "loading" Phänomen.
Ich werde aus deiner Lösung nicht schlau. Wo war das Problem und wo die Lösung?

**Comment by Alexalter** [comment]
Ich weis nicht mehr wo ich runtergeladen BBSmile 3.0.0, aber unter al-werner.de Downloads kann man runterladen
